### ISSUE TITLE
Most recent research outputs?

### ISSUE THREAD

**Issue by drastician** [umdigital/umich-altmetrics#1]
Is there a way to see the most recent research outputs instead of the top research outputs by score?

**Comment by billickc** [comment]
You can do that in Altmetric Explorer (before you generate an API URL). After you do a search, you can change the **Sort by** dropdown to **Publication date (Newest first)**.

![altmetric-sort](https://user-images.githubusercontent.com/752532/48444917-46c69c80-e763-11e8-9bde-5ce40a20843b.jpg)
