### ISSUE TITLE
Use of short tags discouraged

### ISSUE THREAD

**Issue by cajunjoel** [umdigital/umich-altmetrics#2]
According to the [PHP documentation](https://www.php.net/manual/en/language.basic-syntax.phptags.php):

> PHP also allows for short open tag `<? `(which is discouraged since it is only available if enabled using the `short_open_tag` php.ini configuration file directive, or if PHP was configured with the `**--enable-short-tags**` option). 

Due to this, and the fact that some users will have **short_open_tag** disabled, the templates/default.tpl file needs to be updated to use the full <?php ?> tags and to replace `<?=` with `<?php echo `.

**Comment by nobleclem** [comment]
The caveat to that is that as of php 5.4 `<?=` is  always supported.  So looks like I should only need to replace the instances of `<? ` with `<?php `.

**Comment by cajunjoel** [comment]
So it is! I should scroll down more often. :) Agreed only `<?` needs replacing.

**Comment by nobleclem** [comment]
No worries... I thought you were 100% correct and was just wanting to re-read that section for familiarity and saw that change.  Granted I had to read it a couple times to realize that it was `<?=` and not all `<?` usage.  I will try to make that change soon.  I often forget to use `<?php` on public code vs private code as I always turn short tags on.
